"""Centralized HTML ID constants for interaction pattern components"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/core/html_ids.ipynb.

# %% auto 0
__all__ = ['InteractionHtmlIds']

# %% ../../nbs/core/html_ids.ipynb 3
from cjm_fasthtml_app_core.core.html_ids import AppHtmlIds

# %% ../../nbs/core/html_ids.ipynb 5
class InteractionHtmlIds(AppHtmlIds):
    """HTML ID constants for interaction pattern components.
    
    Inherits from AppHtmlIds:
        - MAIN_CONTENT = "main-content"
        - ALERT_CONTAINER = "alert-container"
        - as_selector(id_str) - static method
    """
    
    # Step flow components
    STEP_FLOW_CONTAINER = "step-flow-container"
    STEP_FLOW_PROGRESS = "step-flow-progress"
    STEP_FLOW_CONTENT = "step-flow-content"
    STEP_FLOW_NAVIGATION = "step-flow-navigation"
    
    # Navigation buttons
    STEP_FLOW_BACK_BTN = "step-flow-back-btn"
    STEP_FLOW_NEXT_BTN = "step-flow-next-btn"
    STEP_FLOW_CANCEL_BTN = "step-flow-cancel-btn"
    STEP_FLOW_SUBMIT_BTN = "step-flow-submit-btn"
    
    @staticmethod
    def step_content(step_id: str  # Step identifier
                    ) -> str:  # HTML ID for step content
        """Generate HTML ID for a specific step's content."""
        return f"step-{step_id}-content"
    
    @staticmethod
    def step_indicator(step_id: str  # Step identifier
                      ) -> str:  # HTML ID for step indicator
        """Generate HTML ID for a specific step's progress indicator."""
        return f"step-{step_id}-indicator"
